# Exported from Render on 2024-04-20T17:23:49Z
services:
- type: web
  name: my-type-is-the-bag
  runtime: node
  repo: 
  plan: free
  region: oregon
  buildCommand: npm i
  startCommand: node index.js
version: "1"
